### ISSUE TITLE
Turn portal leads into SweepBright assigned leads

### ISSUE THREAD

**Issue by filipsch** [sweepbright/serverless-mailparser#2]
### Context
The product specification of this project lists out the current situation, the wanted situation, the user stories, and some technical considerations:

https://www.notion.so/sweepbright/Turn-portal-leads-into-SweepBright-assigned-leads-64c4c6d03a3b4effb80be11be91d9ab4

### Todos
- [x] Tackle [todos in product spec](https://www.notion.so/sweepbright/Turn-portal-leads-into-SweepBright-assigned-leads-64c4c6d03a3b4effb80be11be91d9ab4#999f135fd2a4490081a0866231d4d0a1)
- [x] Map out the work on GitHub
   - [x] Create a new GitHub repo that will contain most of the code for this project
   - [x] Move this Epic to that repo
   - [x] Start creating issues as part of that epic. The size of the issues and the amount of detail should just right so everyone involved knows what to do, without investing too much time into prep work.
- [x] Get crackin' on that code :)

**Comment by filipsch** [comment]
For some obscure reason I can't turn this issue into an epic...

**Comment by filipsch** [comment]
@krvajal there is a new endpoint, `/estates/{estateId}/leads` ([link to docs](http://api.dev.sweepbright.com/docs/#company-website-endpoints-create-an-assigned-lead-based-on-an-estate-put)) that allows you to create a specific lead for a project as well. See https://github.com/sweepbright/api/issues/5565 to see how preferences are dervied from the project's details.
