### ISSUE TITLE
Fix parsing of Logic Immo emails

### ISSUE THREAD

**Issue by filipsch** [sweepbright/serverless-mailparser#21]
### Context
- All emails parsed by Logic Immo are failing since December 8, 2019 ([link to dashboard](https://cugor585w0.execute-api.eu-west-1.amazonaws.com/production/home?portal=logicimmo))
- You can find one of the example emails that failed [here](https://www.dropbox.com/s/wgq0ugi7nuim1k1/test.html?dl=0) - screenshot:
  ![image](https://user-images.githubusercontent.com/5768479/70799379-c6310000-1da9-11ea-9217-b1f80fa9f977.png)
- It seems like the SweepBright property id is no longer included, while in the past it was.
- The API currently does not store a mapping of LogicImmo ID to SweepBright property ID, so this probably involves extra work on the API side.

### Todo
- [ ] Confirm that indeed the emails have changed
- [ ] Change API so logic immo reference is stored in `channel_references` table
- [ ] Update maiparser to use the `{{apiUrl}}/channels/logicimmo/channel-references/{id}` endpoint to go from external ref to SweepBright id.

**Comment by filipsch** [comment]
It turns out that the failing parsing was because the LogicImmo publication was done by old software that a new customer of SweepBright used before switching to sweepbright. Obviously, the old publications cannot be linked to SweepBright properties. IMO it doesn't make sense to support this kind of thing; it will not happen often and it's never going to be working 100%; the property details can have changed in the meantime.

**Comment by MatthiasVM** [comment]
@filipsch So it should work for properties published via SweepBright? The property ID is still included?

**Comment by filipsch** [comment]
@MatthiasVM yes.

**Comment by MatthiasVM** [comment]
@filipsch Alright I'll do a new test with Immo Wauters

**Comment by MatthiasVM** [comment]
@filipsch I tried again but it failed in the parser. The property id is included in the email: https://share.getcloudapp.com/z8unx6nG

**Comment by filipsch** [comment]
@MatthiasVM There is indeed something wrong; we'll have to look into this. Thanks for flagging it.

**Comment by filipsch** [comment]
@MatthiasVM I've created a separate issue, as it's different from the issue with the unknown property references. It's here: https://github.com/sweepbright/serverless-mailparser/issues/23

**Comment by filipsch** [comment]
FYI this also happens for immoweb. For clarity: I don't want to do anything about this.
